### ISSUE TITLE
What is the best way to achieve nested json serialisation?

### ISSUE THREAD

**Issue by prog-24** [evermeer/EVReflection#182] opened 2017-04-06 23:46 UTC
I asked this question on [SO](http://stackoverflow.com/questions/43267408/nested-json-to-evreflection-object-swift). I thought I should add it here in case it helps someone

[http://stackoverflow.com/questions/43267408/nested-json-to-evreflection-object-swift](http://stackoverflow.com/questions/43267408/nested-json-to-evreflection-object-swift)

**Comment by evermeer** [comment] 2017-04-12 06:15
**_The copy paste from that SO question is:_**

I am try to create an iOS app, that have a UIWebview and I want to load the website inside it. I try to use EVURLCache for caching. But it doesn't load from the PreCache folder inside my project. 

The app run first time fine. But when I try to run again it shows me blank screen only. I think the app try to load the page from the cache, but the app can't find its caches..

I use https://github.com/evermeer/EVURLCache for caching. And I install via pods

#MainVC

    import UIKit
    
    class MainVC: UIViewController, UIWebViewDelegate {
        @IBOutlet weak var webView: UIWebView!
    
        override func viewDidLoad() {
            super.viewDidLoad()
            webView.delegate = self
            
            let url = URL(string: BASE_URL)
            let request = URLRequest(url: url!)
            
            webView.loadRequest(request)
        }
        
        
        func webViewDidStartLoad(_ webView: UIWebView) {
            print("*****************")
            print(" webViewDidStartLoad(")
            print("*****************")
        }
        
        func webViewDidFinishLoad(_ webView: UIWebView) {
            print("*****************")
            print("webViewDidFinishLoad")
            print("*****************")
        }
    
    }

#AppDelegate

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
            // Override point for customization after application launch.
            EVURLCache.LOGGING = true // We want to see all caching actions
            EVURLCache.MAX_FILE_SIZE = 26 // We want more than the default: 2^26 = 64MB
            EVURLCache.MAX_CACHE_SIZE = 30 // We want more than the default: 2^30 = 1GB
            EVURLCache.activate()
            
            return true
        }

And I found the Cache folder 

    04/10/2017 18:01:41:952 FedNet)[1696:.] EVURLCache.swift(245) storeCachedResponse(_:for:):
    	CACHE save file to Cache  : /Users/apple/Library/Developer/CoreSimulator/Devices/BF935382-BD49-4F37-85A1-C3FA0E1B094B/data/Containers/Data/Application/AF33E59E-1BB4-46CC-9236-BEB42F53D606/Documents/Cache/www.fednetbank.com/corp/l001/consumer/theme/login/img/banner.jpg

[![enter image description here][1]][1]




  [1]: https://i.stack.imgur.com/rL2yM.png

And when I run the app with the PreCache folder it gives me a blank screen....

**Comment by evermeer** [comment] 2017-04-12 06:16
This could be caused by a redirect. Redirects are not cached. I tried to solve that with a protocol but I already noticed that it sometimes fails. Could you try removing the following line from EVURLCache and then try again?

    URLProtocol.registerClass(EVURLProtocol.self)

**Comment by prog-24** [comment] 2017-04-12 22:47
That is not the question, I asked. It was about nested arrays

**Comment by evermeer** [comment] 2017-04-13 06:08
Ah, sorry, I mixed up 2 questions... will clean it up...

**Comment by evermeer** [comment] 2017-04-13 06:11
**_The content of the question is:_**

What is the best way to acheive this using EVReflection

Here is my JSON

```
{
"data": [
{
  "id": "66e67a3e-2465-3aba-9553-b2313e031bb1",
  "title": "Dummy Place",
  "description": "Nulla dolore iusto ut quia corporis sint et. Porro error reiciendis autem.",
  "longitude": "56.0137060000000",
  "country": null,
  "status": 1,
  "created_at": {
    "date": "2017-02-07 21:35:29.000000",
    "timezone_type": 3,
    "timezone": "UTC"
  },
  "updated_at": {
    "date": "2017-02-07 21:35:29.000000",
    "timezone_type": 3,
    "timezone": "UTC"
  },
  "people": {
    "data": [
      {
        "id": "7b56d70c-9e05-3dd1-9372-e0df691a0c89",
        "first_name": "Edd",
        "last_name": "Hauck",
        "username": "wdavis",
      }
    ]
  },
  "programs": {
    "data": [
      {
        "id": "2fff3de7-5660-3da6-86a1-9bc4d21e6615",
        "title": "Ms.",
        "description": "I can kick a little!' She drew her foot slipped, and in another minute the whole head appeared, and then all the right word) '--but I.",
        "price": "22.01"
      }
    ]
  }
},
"meta": {
"cursor": {
  "current": "1",
  "prev": null,
  "next": 2,
  "count": 10
}
}
```

As you can see, each collection is nested in a data container. How can \i represent my object using EVReflection so that every-time it deserialises a collection it knows to deserialise the data element and not the base json. I have achieved this using a pure Alamofire implementation but I am not sure how to do the same with this library.

I would also like some inheritance. Every resource has an id, created_at and updated_at member.

Here is what I have so far.

```
class Model: EVNetworkingObject {

dynamic var id: String?
dynamic var createdAt: Date?
dynamic var updatedAt: Date?


override func propertyMapping() -> [(keyInObject: String?, keyInResource: String?)] {
    return [
            (keyInObject: "id",keyInResource: "id"),
            (keyInObject: "createdAt",keyInResource: "created_at"),
            (keyInObject: "updatedAt",keyInResource: "updated_at")
    ]
}
}
And the subclass

final class Place: Model {
   dynamic var title: String?
  dynamic var desc: String?
  var longitude: Double?
  var latitude: Double?
  dynamic var address1: String?
  dynamic var address2: String?
  dynamic var address3: String?
  dynamic var city: String?
  dynamic var country: String?
  var status: Int8?
  dynamic var people: [User]?
  dynamic var programs: [Procedure]?
}
```
Place inherits id from model so should be serialised.

Here is my Alamofire call:

```
Alamofire.request(Router.allPlaces()).responseArray { (response: DataResponse<[Place]>) in
        if let places = response.result.value {
            self.objects = places
            self.tableView.reloadData()
        }
    }

```

**Comment by evermeer** [comment] 2017-04-13 21:48
I found a small bug that prevented the easiest solution for this. I just pushed it as version 4.8.1
You can find a unit test here: https://github.com/evermeer/EVReflection/blob/master/UnitTests/EVReflectionTests/EVReflectionTests.swift#L480

**Comment by evermeer** [comment] 2017-04-13 22:26
By the way, it works like this:
When a dictionary is found where an array is expected, then when there is only one key in that dictionary that holds an array, then it is assumed that the array should have been used.

**Comment by evermeer** [comment] 2017-04-13 22:28
One other think. you do not have to specify this property mapping:
` (keyInObject: "createdAt",keyInResource: "created_at"),
`
EVReflection has support for automatic snake case to camelCase conversion.
Actually, you don't need any of the property mappings that you specified.

**Comment by evermeer** [comment] 2017-04-13 22:31
And one other thing. You can't use optional types like Int8? or Double? If you do want to have an optional number, then use NSNumber? or just make it non optional and set a default value. (P.S. Optional String and Date are OK)

**Comment by prog-24** [comment] 2017-04-14 01:31
Thanks. Great fix, although I did use the Wrapper method to achieve this I will migrate my code later on to reflect this new update. I figured out the optionals after a couple trial and errors. But I found two new issues I will be posting about later.

**Comment by evermeer** [comment] 2017-04-14 06:14
OK, then I will close this issue and I will see your new issues coming in

**Closed as completed by evermeer** 2017-04-14 06:14 UTC
Labels: fixed?
