### ISSUE TITLE
Nested types lead to problems in obtaining the class name

### ISSUE THREAD

**Issue by CharlinFeng** [evermeer/EVReflection#16] opened 2015-08-16 03:10 UTC
I put in Student class nested inside the Person class, and then get Student instance's class name, problems come:

```
class Person: EVObject {
      class Student: EVObject {
      }
}
```

then,

```
let classString = EVReflection.swiftStringFromClass(Person.Student())
println(classString)
```

Print result is: _TtCC4test6Person7Student

I think the class name results can be encapsulated into an object, such as the object of ordinary class name string, a class name string that contains the namespace, which is more flexible

```
let classStringObj: ClassString = EVReflection.swiftStringFromClass(Person.Student())

classStringObj.shortString //return "Student"

classStringObj.fullString //return "Person.Student"
```

thank you!

**Comment by evermeer** [comment] 2015-08-16 07:38
The swiftStringFromClass is used to generate a string that also can also be used with swiftClassFromString. In previous versions of swift the NSStringFromClass even gave the _TtC.... string for the root object like Person. Apple changed the NSStringFromClass function so that it returns just the app name plus a dot and string of the class itself. So in your case it returns test.Person for the person string and _TtCC4test6Person7Student for the student. Currently I only handle cleaning up test.Person to Person

When creating an alternative method for getting the string I should also create an alternative method for creating a class. How far should that go? because it's also possible to define classes within function. Those strings even look uglier. And then, how should that string be in a nice format.

As you can see, the first part of your nested class is 'test', the name of your app. When working with frameworks, this would be the name of the framework the class is in. So actually I should create a fullString like 'test.Person.Student'. So I guess that classSTringObj of you should have some more functions like: assemblyName (test), className (Student), classPath (Person.Student), fullName (test.Person.Student) and rawName (_TtCC4test6Person7Student) For creating a new class instance I would need the fullName or the rawName or the classPath where is assumed that the assembly name would be the active assembly

I have thought about a cleanup of that string before. but until now there was no need to do so. But indeed it would be nice if there was an easy way to get a better description for a class. It sounds like you even have thought of a functionality that needs this. So... I will put this on my todo list.

**Comment by evermeer** [comment] 2015-08-16 08:25
Ha! Cool work dude! To bad it's not all in English. https://github.com/nsdictionary/CFRuntime

**Comment by CharlinFeng** [comment] 2015-08-16 08:45
Haha！！

The Chinese people, the English level is limited, the trouble you to be patient to read, thank you!

Before I wrote that the framework is also encountered a bad deal optional situation(such as Int?), I would like to ask this question in the swift is no solution?

Some Crash:

The dictionary is ["age": "27"], the model is var age: Int, resulting in a crash,because string cannot convert to Int,
but,the other I would like the framework to detect, and tips,or Automatic convert to Int, rather than crash..

Finally, I think it's great to see your framework, and I decided to abandon my framework, and then, on the basis of your framework, it's very good. I hope you can improve, and can be seen in these two frameworks:

1.https://github.com/kostiakoval/Mirror
2.https://github.com/CoderMJLee/MJExtension (the same,but powerful, and Automatic convert any types)

MJExtension: Automatic convert  and no crash

["age":"15","cost":"200.0","isVip":"1"]

```
class Person{
  var age: Int
  var cost: Float
  var isVip: Bool
  ......
}
```

**Comment by evermeer** [comment] 2015-08-16 10:43
In the current version of EVReflection you can put a number in a string and a string into a number. Yesterday I merged that functionality to the Swift 2.0 branch. I will do some more tests today with the various bool and float values to see if those are all working. If it still crashes, then I will fix that first.

In EVReflection I have 2 workaround test classes that will help you to get around swift limitations like the issue with optional types like Int?

The problem is that the base type of an Int?, enum values an [String?] is of type Any and not AnyObject or NSObject. because of that there is no support for setValue forKey. the only workaround for that is by implementing the setValue forUndefinedKey and setting the property yourself from there. 

It would be awesome If EVReflection was used in other libraries. I am trying to make EVReflection as generic as possible so that it could be use in lots of situations. currently I use it myself in https://github.com/evermeer/EVCloudKitDao for automatic mapping from and to CloudKit objects and I'm also using it in https://github.com/evermeer/AlamofireJsonToObjects to map json results directly to objects. That last library is the used in https://github.com/evermeer/EVWordPressAPI which I am currently writing.

**Comment by evermeer** [comment] 2015-08-16 11:20
In the current version the following tests all pass:

```
    func testTypeJsonAllString() {
        let json:String = "{\"myString\":\"1\", \"myInt\":\"2\", \"myFloat\":\"2.1\", \"myBool\":\"1\"}"
        let a = TestObject4(json: json)
        XCTAssertEqual(a.myString, "1", "myString should contain 1")
        XCTAssertEqual(a.myInt, 2, "myInt should contain 2")
        XCTAssertEqual(a.myFloat, 2.1, "myFloat should contain 2.1")
        XCTAssertEqual(a.myBool, true, "myBool should contain true")
    }

    func testTypeJson2AllNumeric() {
        let json:String = "{\"myString\":1, \"myInt\":2, \"myFloat\":2.1, \"myBool\":1}"
        let a = TestObject4(json: json)
        XCTAssertEqual(a.myString, "1", "myString should contain 1")
        XCTAssertEqual(a.myInt, 2, "myInt should contain 2")
        XCTAssertEqual(a.myFloat, 2.1, "myFloat should contain 2.1")
        XCTAssertEqual(a.myBool, true, "myBool should contain true")
    }

    func testTypeJsonInvalid() {
        let json:String = "{\"myString\":test, \"myInt\":test, \"myFloat\":test, \"myBool\":false}"
        let a = TestObject4(json: json)
        XCTAssertEqual(a.myString, "", "myString should contain 1")
        XCTAssertEqual(a.myInt, 0, "myInt should contain 0")
        XCTAssertEqual(a.myFloat, 0, "myFloat should contain 2.1")
        XCTAssertEqual(a.myBool, true, "myBool should contain true")
    }

    func testTypeDictAllString() {
        let dict = ["myString":"1", "myInt":"2", "myFloat":"2.1", "myBool":"1"]
        let a = TestObject4(dictionary: dict)
        XCTAssertEqual(a.myString, "1", "myString should contain 1")
        XCTAssertEqual(a.myInt, 2, "myInt should contain 2")
        XCTAssertEqual(a.myFloat, 2.1, "myFloat should contain 2.1")
        XCTAssertEqual(a.myBool, true, "myBool should contain true")
    }

    func testTypeDict2AllNumeric() {
        let dict = ["myString":1, "myInt":2, "myFloat":2.1, "myBool":1]
        let a = TestObject4(dictionary: dict)
        XCTAssertEqual(a.myString, "1", "myString should contain 1")
        XCTAssertEqual(a.myInt, 2, "myInt should contain 2")
        XCTAssertEqual(a.myFloat, 2.1, "myFloat should contain 2.1")
        XCTAssertEqual(a.myBool, true, "myBool should contain true")
    }
```

If you find out that something is still failing, then let me know. It would be great if you could also include a unittest for the failure.

**Comment by CharlinFeng** [comment] 2015-08-16 12:17
@evermeer 

AWESOME!

I would like to give you some suggestions, because I am very interested in your project!

（1）. The unification of API
Dictionary transfer to model, the method is able to unify the static call? For example:

Single dictionary to a single model:

```
  let person = Person(dictionary: dict)
```

Dictionary array to model array

```
  let persons: [Person] = Person(dictionaryArray: dicts)
```

（2）. properies ignored:
Like MJExtension, some of the model properties are auxiliary, and do not need to be used in the dictionary to model, you can provide a way to override the static method, such as:

```
    class Person{

      var name: String = ""

      var age: Int = 0

      var pointAddress: String = "" // use for debug

    }

  let dict = ["name":"charlin","age":27]
```

in this case, property  ‘pointAddress’ is not used to read data from the dictionary, it is just a debug attribute, we should ignore it

You can provide a way to let our subclass to rewrite,

```
  class func ignorProperties() -> [String]{

    return [] // ignor Properties
  }
```

（3）. properties replacement
For example, I have a dictionary,

```
  let dict = ["id":1,"name":"charlin","age":27]
```

 and then the model is like this,

```
  class Person{

    var hostID: Int // i hope take out dict key's value named "id"
    var name: String
    var age: Int
    ...
  }
```

May be due to various reasons, the dictionary "id" key I can not use the same property as the model to representative, but the use of another property named hostID to representative, but I hope that this property named hostID is to  take out dict key's value named "id",The model can provide a static method for us to rewrite:

```
  class func replaceDict()->[String: String] {

    return ["hostID":"id"]
  }
```

So now, take out the value from dictionary of the details is this:

```
  "hostID" take out "id" key
  "name" take out "name" key
  "age" take out "age" key
```

（4）.Add this feature the : plist file of the full automatic parse:
      let persons = Person(plistFile: ....)

In the end, there are some things that don't know Whether it is useful for you：
1 in China iCloud access is very slow, Chinese developers use iCloud very little.
2 some developers do not use Alamofire, such as me, I used  network request framework myself.
Finally, thank you sincerely, and look forward to the great improvement!

**Comment by evermeer** [comment] 2015-08-16 12:55
That's a lot of questions :)

One general comment. when you initiate an object with something like let person = Person(dictionary: dict) then that dictionary can even contain sub dictionaries which would initiate it's own nested objects. So you could have a boss property that is also of type Person. Everything would be initiated in just one call.

You can not initiate an object and let it return an array of that object. So the following line will never work:
`let persons: [Person] = Person(dictionaryArray: dicts)`
What is possible in EVReflection is this:
`let persons: [Person] = EVReflection.arrayFromJson(Person(), json: jsonDictOriginal)`
where jsonDictOriginal is a json string that has an array as it's root element.
What you want in your case is something like this:
`let persons: [Person] = dicts.map({Person(dict: $0)})`

With EVReflection you do not need to initiate the object with a dictionary. You can also just initiate the object. If you do initiate it with a dictionary, then it's ok to have a dictionary with as many properties defined as you like. You could just set 1 property or you could set them all. but when you create a dictionary from that object, it will include all properties, including your debug properties. Let me first think about what would be the best way to let you exclude some properties. 

That replace property names dictionary is also a good idea. I will think about how to implement this together with the ignore properties feature of the issue above.

And then your tips:
1. Ah, never thought about a regional (China) slow iCloud / CloudKit. When CloudKit was presented a year ago I thought it was great easy way to implement a database and push notifications. That's why I created EVCloudKitDao. EVReflection was created because of EVCloudKitDao. At first all the code was in EVCloudKitDao. I extracted EVReflection because I saw the potetial of such a library.
2. I created AlamoFireJsonToObjects because it was so easy to create. That library is only one small class with less than 100 lines of code of which half of it is comments. EVReflection can easily be used with any networking library or custom code. 

I have to thank you for your great response on EVReflection. Until now most of the features are created because I thought there could be a need for it. Now I have got some great ideas from your response. This will allow me to make the library even better.

**Comment by evermeer** [comment] 2015-08-19 11:00
I just pushed version 2.6.0 to github (only trunk, no swift 2 yet) with support for custom property mapping. You can now map properties like this:

```
public class TestObject5: EVObject {
    var Name: String = "" // Using the default mapping
    var dummyPropertyInObject: String = "" // Will not be written from object to targe but will be written to object if exist in dictionary or json
    var propertyInObject: String = "" // will be written to or read from keyInJson
    var ignoredProperty: String = "" // Will not be written to object or from object to target

    override public func propertyMapping() -> [(String?, String?)] {
        return [("ignoredProperty",nil), (nil,"ignoredProperty"), ("dummyPropertyInObject",nil), (nil,"dummpyKeyInJson"), ("propertyInObject","keyInJson")]
    }
}
```

So now the last thing to do from your list of feature request is the cleanup of the class name for nested objects.

**Comment by evermeer** [comment] 2015-08-19 21:16
I just pushed my code to GitHub. It's not yet a new cocoa pod version just download the trunk.
There is a TODO in the code for reverse engineering the descriptions for functions.

**Comment by nobre84** [comment] 2015-08-23 15:32
Hi! Great work you got here! I liked the new addition (ignored and/or remapped properties), when will you push a new podspec ??
I have seen in some other libraries the option to auto convert between camelCase <-> undersscore_case that is so common in back end systems, do you think it might be worthy adding that feature ?

**Comment by evermeer** [comment] 2015-08-23 15:50
Ah @nobre84 I just 'forgot' to update the cocoapod version for that. 

update: hmm... I see it's already there in version 2.6.0.
the feature is not yet in the swift 2 branch.

Besides that you could always force to get the trunk version by specifying:
pod 'EVReflect' , :trunk

Indeed that automatic name conversion sounds like a nice addition. Let me think about how I should implement such an automatic property - key conversion. My first impression would be that you should be able to specify what kind of notation you would like in both the object as the target. Can you think of any other casing besides these 3? camelCase, PascalCase, undersocer_case

**Comment by nobre84** [comment] 2015-08-25 01:54
Thank you, I just needed an update on my local pod :flushed: 
Regarding the auto conversion, I think those 3 are the most relevant. Some others are available for instance in [Google's GSON](http://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/FieldNamingPolicy.html), but are not that common to see.

**Comment by evermeer** [comment] 2015-09-04 09:07
Now in the Swift 2 branch there is also the option to convert between camelCase and snake_case
https://github.com/evermeer/EVReflection/tree/Swift2#automatic-keyword-mapping-pascalcase-or-camelcase-to-snake_case

**Comment by evermeer** [comment] 2015-09-30 09:45
The new EVObjectDescription object will now give you enough information from the internal Swift class name. When using a class definition within a function definition there are still some issues. But the string format is hard to reverse engineer. You should also not use a structure like that in your application. 

In my opinion this is now good enough for 99.99% of all cases. I probably can make it perfect after swift is released as open source. So I will close this issue. If you don't agree, then just tell me your use case and I will reopen this and I will try to fix that for you.

**Closed as completed by evermeer** 2015-09-30 09:45 UTC
Labels: enhancement
