### ISSUE TITLE
Nested Generics

### ISSUE THREAD

**Issue by Twinsens** [evermeer/EVReflection#114] opened 2016-08-02 12:10 UTC
Hello 

Is that possible nested generics in EVReflection? I was tested code that the following but it not work. Could you help me about the issue?

```
class ResponseModel<T:BaseModel> : EVObject,EVGenericsKVC {    

      required init() {
          super.init();
        }

    var success : String?;
    var reason : String?
    var content : [T]?;


    internal override func setValue(value: AnyObject!, forUndefinedKey key: String) {
        if(key == "content"){
            content = value as? [T];
        }
    }

}


class PagerModel<T:BaseModel>: BaseModel,EVGenericsKVC{    
    required init() {
        super.init();
    }

    var total:String?;
    var per_page:String?;
    var current_page:String?;
    var last_page:String?;
    var next_page_url:String?;
    var prev_page_url:String?;
    var from:String?;
    var to:String?;
    var data:[T]?;


       internal  override func setValue(value: AnyObject!, forUndefinedKey key: String) {
        if(key == "data"){
        data = value  as? [T];
        }
    }




class BaseWebServices<T:BaseModel> : NSObject  {

    let BASE_URL : String! = "http://localhost/IOS/public/api/v1/";

    var listener : ResponseListener?;



    func executeService(serviceUrl : String, method : Alamofire.Method,parameters: [String: AnyObject]){

        let URL : String = "\(self.BASE_URL)\(serviceUrl)";
        Alamofire.request(method, URL, parameters:parameters)
            .responseObject { (response: Result<ResponseModel<T>, NSError>) in

                switch response{
                case .Success( _)  :
                    if let result : ResponseModel<T> = response.value {
                        self.listener?.onResponseSuccess(result);
                    }
                    break;
                case .Failure(let error) :
                    self.listener?.onResponseFail(error)
                    break;
                }
        }



    }


class NewsHeaderService: BaseWebServices<PagerModel<NewsHeader>>,ResponseListener {

    override  init() {
        super.init();
        super.listener = self;


        executeService("getNewsHeadersByPrjId/1", method: .POST, parameters: ["token":Common.TOKEN_KEY])
    }

    func onResponseSuccess<T : BaseModel where T : protocol<ObjectProtocol>>(object: ResponseModel<T>) {

    }



    func onResponseFail(failMessage: NSError) {

    }
}


class NewsHeader : BaseModel{   

    var id : String?;
    var Description: String?;
    var newsTypeId:String?;
    var newsOrder : String?;
    var isCommentActive : String?;
    var placeTypeId : String?;
    var link : String?;
    var title : String?; 
    var pubDate : String?;
    var imageUrl : String?;
    var imageThumUrl : String?;
    var appId : String?;
    var projectId : String?;
    var isValid : String?;
    var created_at : String?;
    var updated_at : String?;
}
```

When I try to execute 

`var service : NewsHeaderService = NewsHeaderService();`

There was an error,

ERROR: Could not create an instance for type PagerModel<NewsHeader>
dict:{
    "current_page" = 1;
    data =     (
                {
            appId = 1;
            "created_at" = "2016-06-29 12:15:23";
            description = 33333;
            id = 1;
            imageThumUrl = "";
            imageUrl = "uploads/74d41d1a8b39541ce2e7b6fc1f844ef0_04_IP-MAN-3_Courtesy-of-Well-Go-USA_0-752x440.jpg";
            isCommentActive = 1;
            isValid = 1;
            link = 11111;
            newsOrder = 0;
            newsTypeId = 2;
            placeTypeId = 1;
            projectId = 1;
            pubDate = "";
            title = 22222;
            "updated_at" = "2016-06-29 12:15:23";
        }
    );
    from = 1;
    "last_page" = 1;
    "next_page_url" = "<null>";
    "per_page" = 15;
    "prev_page_url" = "<null>";
    to = 1;
    total = 1;
}

If I change `class PagerModel<T:BaseModel>` to`class PagerModel` and remove "data" property it works fine but I need the data :) Can anybody help me about my issue? Thanks for your time.

Edit: Here is parsed JSON data

{"success":true,"reason":"OK","content":[{"total":1,"per_page":15,"current_page":1,"last_page":1,"next_page_url":null,"prev_page_url":null,"from":1,"to":1,"data":[{"id":1,"newsTypeId":"2","newsOrder":"0","isCommentActive":"1","placeTypeId":"1","link":"11111","title":"22222","description":"33333","pubDate":"","imageUrl":"uploads\/74d41d1a8b39541ce2e7b6fc1f844ef0_04_IP-MAN-3_Courtesy-of-Well-Go-USA_0-752x440.jpg","imageThumUrl":"","appId":"1","projectId":"1","isValid":"1","created_at":"2016-06-29 12:15:23","updated_at":"2016-06-29 12:15:23"}]}]}

**Comment by evermeer** [comment] 2016-08-03 13:37
I think I will have to make a unit test for this to see where it goes wrong...

**Comment by Twinsens** [comment] 2016-08-03 13:42
Thank you for your good library that called EVReflection. I will wait for the results. Thank you again.

**Comment by evermeer** [comment] 2016-08-03 14:48
I could reproduce your issue. It looks like there is indeed an issue with creating generic object.
The code is trying to create an instance of `PagerModel<NewsHeader>`
But internally (Swift) that class is called `_TtGC27AlamofireJsonToObjectsTests10PagerModelCS_10NewsHeader_`
I have to find out if I can get that true type from code.

**Comment by Twinsens** [comment] 2016-08-04 12:40
@evermeer firstly thank you for your time.

Today I studied a little about your results. I found something look like interesting,

`PagerModel<NewsHeader<AppSettings>>()`

_TtGC12Swift3Deneme10PagerModelGCS_10NewsHeaderCS_11AppSettings__

`PagerModel<NewsHeader>()`

_TtGC12Swift3Deneme10PagerModelCS_10NewsHeader

You can take a look these 2 generated results. There are relation between them,

For example;

 `PagerModel<NewsHeader<AppSettings>>()`
 When we parse this like;

```
        var firstClass = "PagerModel";
        var secondClass = "NewsHeader";
        var thirdClass = "AppSettings";
```

If we want to generate internally (Swift) ;

`var classString : String = "TtGC\(APPLICATION_NAME.utf16.count)\(APPLICATION_NAME)\(firstClass.utf16.count)\(firstClass)GCS_\(secondClass.utf16.count)\(secondClass)CS_\(thirdClass.utf16.count)\(thirdClass)__";`

But I think there must be much more easier method But I can not find. This algorithm will create our class instance. It works.

**Comment by evermeer** [comment] 2016-08-04 12:56
this could be a partial fix but I would like it to work with whatever is used in the generics type. Even with multiple levels of nested generics. I'm away for a couple of days so I probably cannot pick it up before next monday.

**Comment by evermeer** [comment] 2016-08-10 20:38
I just pushed a workaround fix for this as release 2.45.0 to GitHub and CocoaPods.

With EVGenericsKVC you now also always have to add these lines of code:

```
public func getGenericType() -> NSObject {
     return T()
 }
```

Your issue has been added as a unit test in AlamofireJsonToObjects. You can find it here:
https://github.com/evermeer/AlamofireJsonToObjects/blob/5193a3e5f704b117990d0ded06983b883bb20fc7/AlamofireJsonToObjectsTests/NestedGenericsIssue25.swift#L140-L140

**Comment by Twinsens** [comment] 2016-08-11 06:27
@evermeer  First of all thanks for your time. Your update definitely works. Respects from Turkey 👍

**Closed as completed** 2016-08-11 10:57 UTC
Labels: fixed?

**Comment by groovedev** [comment] 2016-10-06 06:14
Hi Edwin, 

When I run the simple test from EVReflection Reference, I have an issue with the nested arrays, Company and Friends.
http://cocoadocs.org/docsets/EVReflection/2.4.8/

I'm using EVReflection (2.46.0)

Initial dictionary:
["email": john@appleseed.com, "id": 24, "friends": <_TtCs21_SwiftDeferredNSArray 0x145b4820>(
{
    id = 27;
    name = "Bob Jefferson";
},
{
    id = 29;
    name = "Jen Jackson";
}
)
, "company": {
    address = "1 Infinite Loop, Cupertino, CA";
    name = Apple;
}, "name": John Appleseed]

ERROR: Could not create an instance for type User
dict:{
    id = 27;
    name = "Bob Jefferson";
}
ERROR: Could not create an instance for type User
dict:{
    id = 29;
    name = "Jen Jackson";
}
ERROR: Could not create an instance for type Company
dict:{
    address = "1 Infinite Loop, Cupertino, CA";
    name = Apple;
}

WARNING: The class '_TtCC9mySmartRG23EquipmentViewController4User' is not key value coding-compliant for the key 'company'
 There is no support for optional type, array of optionals or enum properties.
As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information

**Comment by evermeer** [comment] 2016-10-06 09:19
Did you implement the EVGenericsKVC protocol on the User object?
Does it work when you first call  `EVReflection.setBundleIdentifier(User)` ? 
Could you show me the test code that you used (including the User class definition)?

**Comment by groovedev** [comment] 2016-10-06 20:58
// pod 'EVReflection'

```
class User: EVObject {
    var id: Int = 0
    var name: String = ""
    var email: String?
    var company: Company?
    var friends: [User] = []
}

class Company: EVObject {
    var name: String = ""
    var address: String?
}

override func viewDidLoad()
{
    super.viewDidLoad()       

    let jsonDictOriginal = [
        "id": 24,
        "name": "John Appleseed",
        "email": "john@appleseed.com",
        "company": [
            "name": "Apple",
            "address": "1 Infinite Loop, Cupertino, CA"
        ],
        "friends": [
            ["id": 27, "name": "Bob Jefferson"],
            ["id": 29, "name": "Jen Jackson"]
        ]
    ]
    print("Initial dictionary:\n\(jsonDictOriginal)\n\n")

    let userOriginal = User(dictionary: jsonDictOriginal)

    let jsonString = userOriginal.toJsonString()
    print("JSON string from dictionary: \n\(jsonString)\n\n")
}
```

****\* RESULT *****

Initial dictionary:
["email": john@appleseed.com, "id": 24, "friends": <_TtCs21_SwiftDeferredNSArray 0x1460a140>(
{
    id = 27;
    name = "Bob Jefferson";
},
{
    id = 29;
    name = "Jen Jackson";
}
)
, "company": {
    address = "1 Infinite Loop, Cupertino, CA";
    name = Apple;
}, "name": John Appleseed]

ERROR: Could not create an instance for type User
dict:{
    id = 27;
    name = "Bob Jefferson";
}
ERROR: Could not create an instance for type User
dict:{
    id = 29;
    name = "Jen Jackson";
}
ERROR: Could not create an instance for type Company
dict:{
    address = "1 Infinite Loop, Cupertino, CA";
    name = Apple;
}

WARNING: The class '_TtCC9mySmartRG23EquipmentViewController4User' is not key value coding-compliant for the key 'company'
 There is no support for optional type, array of optionals or enum properties.
As a workaround you can implement the function 'setValue forUndefinedKey' for this. See the unit tests for more information

JSON string from dictionary: 
{
  "name" : "John Appleseed",
  "id" : 24,
  "company" : null,
  "email" : "john@appleseed.com",
  "friends" : [

  ]
}

**Comment by evermeer** [comment] 2016-10-08 12:47
@groovedev I just pasted your code into a project that uses version 3.0.3  (Swift3 branch) and it worked ok. I only had to cast jsonDictOriginal to NSDictionary. I don't have XCode 7 anymore, so I can't test the 2.46.0 version anymore.

I find it strange that you get this warning:
WARNING: The class '_TtCC9mySmartRG23EquipmentViewController4User' is not key value coding-compliant for the key 'company'
Because that implies that it able to create a User object, but the is not able to set the company.
But then if its able to create a User then why do you get this error:
ERROR: Could not create an instance for type User

Ah wait... I see that your user Class is defined inside your EquipmentViewController class. Could you try moving that definition out of that class? So that User is not a subclass of EquipmentViewController class?

Ah, yes, that was it.... I just did an other test and I got the same result as you. I will try to recreate that issue in a unit test in the EVReflection library and see if I can fix it. 

For now the workaround is to move your class definitions out of other class definitions. 

Since this is an other issue, I created issue #129 for this

**Comment by groovedev** [comment] 2016-10-08 21:58
Ahh, yes, that was the issue. Thanks.
