### ISSUE TITLE
Memory leaks with setObjectValue function

### ISSUE THREAD

**Issue by lytieunuong1** [evermeer/EVReflection#272] opened 2018-03-14 02:25 UTC
I used instruments and found memory leaks at **setObjectValue** function cause this line:
```swift
try anyObject.validateValue(&setValue, forKey: key)
```
this is a picture I captured when I used instruments
<img width="1277" alt="screen shot 2018-03-14 at 8 59 25 am" src="https://user-images.githubusercontent.com/12498638/37379991-0b310364-2769-11e8-85fa-f70654abb990.png">

As I know **validateValue** is a function of Foundation Framework, so I don't know why it got leaks here. Do we have another function to replace this?

**Comment by evermeer** [comment] 2018-03-14 09:21
the .validateValue will call all validate functions that are implemented on the anyObject. Do you have a validate function in your object? Maybe the setValue is retained within that validation function?

There is not really an alternative for the .validateValue. It uses reflection to see if there is a validate function for that key and then call that function. For more info see https://developer.apple.com/documentation/objectivec/nsobject/1416754-validatevalue

**Comment by evermeer** [comment] 2018-03-26 15:14
where you able to see if you indeed implemented a validation function and if the memory leek caused by that?

**Comment by hanshamm** [comment] 2018-04-18 17:37
Is there any solution for this ?

**Comment by evermeer** [comment] 2018-04-19 04:36
@hanshamm I am not able to reproduce this issue. I need more info from @lytieunuong1 to see if I can reproduce this.

**Comment by evermeer** [comment] 2018-04-30 05:25
I will close this issue now. If you are able to reproduce this, then pleas let me know how so that I can investigate that.

**Closed as completed by evermeer** 2018-04-30 05:25 UTC

**Comment by MikeManzo** [comment] 2018-06-09 13:11
I am seeing the same behavior with my implementation.  I am constantly leaking 100 byes per instance and it's (so far) been traced back to this very line.  I am using:
EVReflection: 5.6.1
Swift: 4
Deployment Target: 10.11

**Comment by evermeer** [comment] 2018-06-10 10:59
There is a memory leak issue with the implementation of the validateValue
Here is the associated radar: http://www.openradar.me/37115134

Since it only leaks if the validation function is not implemented the only thing I had to do is to test to see if there was a validation function. So I changed the code to:

```
            do {
                if !(value is NSNull) {
                    var setValue: AnyObject? = value as AnyObject?
                    let validateFunction = "validate" + key.prefix(1).uppercased() + key.dropFirst() + ":error:"
                    if (anyObject as AnyObject).responds(to: Selector(validateFunction)) {
                        try anyObject.validateValue(&setValue, forKey: key)
                    }
                    anyObject.setValue(setValue, forKey: key)
                }
            } catch _ {
```

I just pushed it to GitHub as release 5.6.2. The Cocoapods publish is now running and should be ready in about half an hour.

**Comment by MikeManzo** [comment] 2018-06-10 21:23
I was *just* coming here to tell you that if your subclass simply has an empty override for validateValue, the leak does not manifest.  Well done.  Thanks for the quick turn!

    override func validateValue(_ ioValue: AutoreleasingUnsafeMutablePointer<AnyObject?>, forKey inKey: String) throws {
        // Do nothing, leak goes away
    }

**Comment by thepinyo** [comment] 2018-11-05 05:14
i am seeing same issue
- Iphone 6 plus(simulator), iOS 11.2
- Swift 4 
 - EVReflection/Alamofire (5.5.6):
    - Alamofire
    - EVReflection/Core
  - EVReflection/Core (5.5.6)
  - EVReflection/Moya (5.5.6):
    - EVReflection/Alamofire
    - Moya
  - EVReflection/MoyaRxSwift (5.5.6):
    - EVReflection/Moya
    - Moya/RxSwift

![screen shot 2561-11-05 at 12 05 33](https://user-images.githubusercontent.com/10898349/47979197-4b041180-e0f4-11e8-8119-8ec124ed61f5.png)
![screen shot 2561-11-05 at 12 05 49](https://user-images.githubusercontent.com/10898349/47979198-4b041180-e0f4-11e8-8ac4-a45227d105ef.png)

**Comment by evermeer** [comment] 2018-11-05 06:03
@thepinyo You are using an older version of EVReflection where the validateValue was not called conditionally. If you are not able to go to the latest version, then you could solve this issue by replacing the do - catch piece of code from your last screenshot to:

```
           do {
                if !(value is NSNull) {
                    var setValue: AnyObject? = value as AnyObject?
                    let validateFunction = "validate" + key.prefix(1).uppercased() + key.dropFirst() + ":error:"
                    if (anyObject as AnyObject).responds(to: Selector(validateFunction)) {
                        try anyObject.validateValue(&setValue, forKey: key)
                    }
                    anyObject.setValue(setValue, forKey: key)
                }
            } catch _ {
```
As you can see the validate value is only called when it's implemented.
