### ISSUE TITLE
Cannot access init()

### ISSUE THREAD

**Issue by joshuaavalon** [evermeer/EVReflection#200] opened 2017-05-17 09:34 UTC
When I create a class extend `EVObject` , I can only access `init(coder: NSCoder)` and `init()`. It cannot find `init(json: json)` or `init(dictionary: dict)`

**Comment by evermeer** [comment] 2017-05-17 11:33
Don't you get any build errors?

Do you import EVReflection at the top of your file?

`import EVReflection`

And if you click EVObject and right click on it and select 'jump to definition' do you see the EVObject class that implements EVReflectable?

**Comment by joshuaavalon** [comment] 2017-05-17 11:48
> Don't you get any build errors?

No

> Do you import EVReflection at the top of your file?

Yes

As I have mentioned, I can access `init(coder: NSCoder)` and `init()` including `EVObject`. I know there is  `init(json: json)` in the extension but I don't know why Xcode cannot recognize it. I install it through cocoapods.

**Comment by evermeer** [comment] 2017-05-17 13:21
Hmmm... Must be a dependency issue... Still strange you don't get a build error then. 
In your podfile, did you add EVReflection to the target that you are trying to build?
You don't get a build error when you do:
   ` let o = EVObject()`
I'm puzzled what this could be.
If you do a pod update, is it version 4.13.0 that you see as the installed version?

**Comment by joshuaavalon** [comment] 2017-05-17 13:53
Yes, I sure it is 4.13.0
I am even added `'~> 4.13.0'` to my podfile

**Comment by evermeer** [comment] 2017-05-30 19:20
I can't reproduce this issue... Is anyone else having this problem?

**Comment by evermeer** [comment] 2017-06-06 19:12
Closing this for now. Reopen this if it's still an issue. Please provide a reproduction path.

**Closed as completed by evermeer** 2017-06-06 19:12 UTC
Labels: Cannot reproduce

**Comment by tonespy** [comment] 2017-07-01 00:37
I have been experiencing the same thing for over an hour now. And I can see all the supported init method. But, only `init(coder: NSCoder)` and `init()` is present. Clean Built the Directory, reinstalled the pods. Nothing worked

Method Access
<img width="977" alt="screen shot 2017-07-01 at 1 45 14 am" src="https://user-images.githubusercontent.com/3057485/27757850-2a9a67ce-5dff-11e7-883a-38fe3eb4a877.png">

After initialization

<img width="995" alt="screen shot 2017-07-01 at 1 48 14 am" src="https://user-images.githubusercontent.com/3057485/27757864-66fa2a42-5dff-11e7-8a54-aaae76b01fc2.png">

Including the EVObject

<img width="986" alt="screen shot 2017-07-01 at 2 25 35 am" src="https://user-images.githubusercontent.com/3057485/27758095-9ff8c40c-5e04-11e7-86d7-186f29b04300.png">

Platform
Xcode 9.0 Beta
Swift 3.2

**Comment by tonespy** [comment] 2017-07-01 07:09
So, I decided to typecast the key, value pair with `NSDictionary` and everything works fine E.g: `EVObject(dictionary: result.response as NSDictionary)`

**Comment by evermeer** [comment] 2017-07-01 08:50
@tonespy Strange that the compiler asks you to call another function instead of casting to a base type. Glad to hear its solved now.
