### ISSUE TITLE
Range(at:) has been renamed to rangeAt(_:)

### ISSUE THREAD

**Issue by tomasznazarenko** [evermeer/EVReflection#254] opened 2017-11-22 16:34 UTC
https://github.com/evermeer/EVReflection/blob/7c1dd7608f9778156e621c79452e9bd7cc27e742/Source/EVReflection.swift#L1580

`range(at:)` has been renamed to `rangeAt(_:)`

let dateString = (fromDateTimeString as NSString).substring(with: match.rangeAt(1))     // Extract milliseconds

**Comment by evermeer** [comment] 2017-11-23 21:49
`range(at:)` is introduced in Swift 4. If you want to use the latest version of EVReflection then you need to update your app to use Swift 4

**Comment by evermeer** [comment] 2017-11-23 21:59
This issue is a duplicate of https://github.com/evermeer/EVReflection/issues/249

According to the documentation it should be `range(at:)`
Or am I missing something?

**Closed as completed** 2017-11-23 22:26 UTC
Labels: duplicate
